name       : linux-steam-integration
version    : '0.6'
homepage   : https://github.com/solus-project/linux-steam-integration
release    : 1
source     :
    - git|https://github.com/solus-project/linux-steam-integration.git : 80603598af306c5fcbd4a107dd8cab694cc79629
license    : LGPL-2.1
component  : games
summary    : Helper for enabling better Steam integration on Linux
description: |
    A helper shim to enable better Steam* integration on Linux systems. This is part of an effort by Solus to enhance Steam for everyone.
builddeps  :
    - pkgconfig(gtk+-3.0)
emul32     : yes
libsplit   : no
patterns   :
    - /usr/lib32  # LSI is required by Steam so you need 32-bit anyway.
setup      : |
    COMMONOPTS="-Dwith-libressl-mode=shim -Dwith-libressl-suffix=-libressl -Dwith-snap-support=true"
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        # 32-bit build, default to building only libintercept
        %meson_configure -Dwith-shim=none $COMMONOPTS
    else
        # Enable frontend and shim for the 64-bit build
        %meson_configure -Dwith-shim=replacement -Dwith-frontend=true -Dwith-steam-binary=/usr/lib/steam/steam $COMMONOPTS
    fi
build      : |
    %meson_build
install    : |
    %meson_install

    if [[ -z "${EMUL32BUILD}" ]]; then
        # These are needed by the snap itself
        install -m 00755 $pkgfiles/*.sh $installdir/usr/bin/.

        # Let's make our .desktop files available shall we..
        install -D -d -m 00755 $installdir/meta/gui
        mv $installdir/usr/share/applications/*.desktop $installdir/meta/gui/.
        rmdir $installdir/usr/share/applications

        # TODO: Restore settings!
        rm -v $installdir/meta/gui/lsi-settings.desktop

        # meson mandates prefix/bin ...
        install -D -d -m 00755 $installdir/bin
        mv $installdir/usr/bin/* $installdir/bin/.

        # Exported command goes into /
        mv $installdir/bin/steam $installdir/linux-steam-integration
        rmdir $installdir/usr/bin
    fi
