name       : mesalib
version    : 17.3.0_rc3
release    : 72
source     :
    - https://mesa.freedesktop.org/archive/mesa-17.3.0-rc3.tar.xz : 1f3677429018f6ef4167b31db9eef558827a649239aa685f54c1a400ff5462d9
homepage   : http://mesa3d.org/
license    :
    - BSL-1.0
    - MIT
    - SGI-B-1.0
component  : xorg.display
summary    :
    - Mesa is an OpenGL compatible 3D graphics library.
    - demos: Mesa demonstration binaries
optimize   : speed
emul32     : yes
builddeps  :
    - pkgconfig(dri2proto)
    - pkgconfig(dri3proto)
    - pkgconfig32(expat)
    - pkgconfig(glproto)
    - pkgconfig32(libdrm)
    - pkgconfig32(libelf)
    - pkgconfig32(libva)
    - pkgconfig32(nettle)
    - pkgconfig(presentproto)
    - pkgconfig32(vdpau)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig32(xext)
    - pkgconfig32(xdamage)
    - pkgconfig32(xfixes)
    - pkgconfig32(xxf86vm)
    - pkgconfig32(xcb-dri3)
    - pkgconfig32(xshmfence)
    - pkgconfig32(x11)
    - pkgconfig32(zlib)
    - llvm-32bit
    - llvm-devel
    - mako
    - git
    - vim
patterns   :
    - demos:
        - /usr/bin
        - /usr/share/man
description: |
    Mesa is an OpenGL compatible 3D graphics library.
setup      : |
    %apply_patches
    %configure --disable-static \
               --with-clang-libdir=%libdir%/clang \
               --sysconfdir=/etc \
               --enable-texture-float \
               --enable-egl \
               --enable-gles1 \
               --enable-gles2 \
               --enable-vdpau \
               --enable-xa \
               --enable-gbm \
               --enable-gallium-egl \
               --enable-gallium-gbm \
               --enable-llvm \
               --enable-glx-tls \
               --enable-nine \
               --enable-gallium-osmesa \
               --with-llvm-shared-libs \
               --enable-shared-glapi \
               --with-vulkan-drivers=intel,radeon \
               --with-egl-platforms="drm,x11,wayland" \
               --with-gallium-drivers="nouveau,r300,r600,radeonsi,svga,swrast,swr,virgl" \
               --enable-dri3
build      : |
    unset LD_AS_NEEDED
    %make
    if [[ -z "${EMUL32BUILD}" ]]; then
        %make -C xdemos DEMOS_PREFIX=/usr
    fi
install    : |
    unset LD_AS_NEEDED
    %make_install
    if [[ -z "${EMUL32BUILD}" ]]; then
        %make_install -C xdemos DEMOS_PREFIX=/usr
    fi

    # Move all of the libGL/libEGL out of the libdir into a subdir to ensure it
    # follows Solus requirements (LDM managed or in the case of snapd, out of the
    # way of any overlayed hostfs nvidia drivrs
    install -d -D -m 00755 $installdir/%libdir%/glx-provider/default
    mv -v $installdir/%libdir%/lib{EGL,GL}*.so* $installdir/%libdir%/glx-provider/default/.
    
