name       : mesalib
version    : 17.3.0_rc4
release    : 100
source     :
    - https://mesa.freedesktop.org/archive/mesa-17.3.0-rc4.tar.xz : 90c9283caa21c047aef013395776ca44037662450bbed188b4eea679084239be
homepage   : http://mesa3d.org/
license    :
    - BSL-1.0
    - MIT
    - SGI-B-1.0
component  : xorg.display
summary    : Mesa is an OpenGL compatible 3D graphics library.
optimize   :
    - speed
    - lto
emul32     : yes
libsplit   : no
builddeps  :
    - pkgconfig(dri2proto)
    - pkgconfig(dri3proto)
    - pkgconfig32(expat)
    - pkgconfig(glproto)
    - pkgconfig32(libdrm)
    - pkgconfig32(libelf)
    - pkgconfig32(libva)
    - pkgconfig32(nettle)
    - pkgconfig(presentproto)
    - pkgconfig32(vdpau)
    - pkgconfig(wayland-client)
    - pkgconfig32(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig32(xext)
    - pkgconfig32(xdamage)
    - pkgconfig32(xfixes)
    - pkgconfig32(xxf86vm)
    - pkgconfig32(xcb-dri3)
    - pkgconfig32(xshmfence)
    - pkgconfig32(x11)
    - pkgconfig32(zlib)
    - llvm-32bit
    - llvm-devel
    - mako
    - git
    - vim
description: |
    Mesa is an OpenGL compatible 3D graphics library.
setup      : |
    unset LD_AS_NEEDED
    %apply_patches
    %configure --disable-static \
               --with-clang-libdir=%libdir%/clang \
               --sysconfdir=/etc \
               --enable-texture-float \
               --enable-egl \
               --enable-gles1 \
               --enable-gles2 \
               --enable-vdpau \
               --enable-xa \
               --enable-gbm \
               --enable-gallium-egl \
               --enable-gallium-gbm \
               --enable-llvm \
               --enable-glx-tls \
               --enable-nine \
               --enable-gallium-osmesa \
               --with-llvm-shared-libs \
               --enable-shared-glapi \
               --with-vulkan-drivers=intel,radeon \
               --with-egl-platforms="drm,x11,wayland" \
               --with-gallium-drivers="nouveau,r300,r600,radeonsi,svga,swrast" \
               --enable-dri3
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install

    # Move all of the libGL/libEGL out of the libdir into a subdir to ensure it
    # follows Solus requirements (LDM managed or in the case of snapd, out of the
    # way of any overlayed hostfs nvidia drivrs
    install -d -D -m 00755 $installdir/%libdir%/glx-provider/default
    mv -v $installdir/%libdir%/lib{EGL,GL}*.so* $installdir/%libdir%/glx-provider/default/.
