name       : glew16
version    : '1.6'
release    : 1
source     :
    - http://jaist.dl.sourceforge.net/project/glew/glew/1.6.0/glew-1.6.0.tgz : bea2a7e9bb97a7a5054d4a65d16aaeedeaa091719359ad3fcd9bfdb0fe8eb7fa
license    :
    - BSD-3-Clause
    - MIT
component  : binary.compat
emul32     : yes
summary    : libGLEW.so.1.6 (Binary Compatibility Library)
description: |
    Binary Compatibility Library - it is forbidden to build against this library
builddeps  :
    - pkgconfig32(xmu)
    - pkgconfig32(xi)
    - pkgconfig32(glu)
    - pkgconfig32(gl)
    - pkgconfig32(xext)
    - pkgconfig32(x11)
setup      : |
    %patch -p1 < $pkgfiles/0001-Underp-buildsystem.patch
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        libdir="lib32"
        ARCH64="false"
    else
        libdir="lib64"
        ARCH64="true"
    fi
    %make CC="${CC}" LD="${CC}" ALIBDIR="${libdir}" ARCH64="${ARCH64}"
install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        libdir="lib32"
        ARCH64="false"
    else
        libdir="lib64"
        ARCH64="true"
    fi
    %make_install CC="${CC}" LD="${CC}" ALIBDIR="${libdir}" ARCH64="${ARCH64}" GLEW_DEST="$installdir/usr"
    # Don't want this stuff in snap
    rm -vf "$installdir"/%libdir%/*.a
    rm -vf "$installdir"/%libdir%/*.so
    rm -rvf "$installdir"/%libdir%/pkgconfig
    rm -rvf "$installdir"/usr/include
