name       : steam
version    : 1.0.0.54
release    : 1
source     :
    - http://repo.steampowered.com/steam/pool/steam/s/steam/steam_1.0.0.54.tar.gz : 42531bf2615afed54c333ae9afeebe8cb68a31304ddfcf90e61b3532a5597386
license    : Distributable
component  : games
summary    : Launcher for the Steam software distribution service
description: |
    Launcher for the Steam software distribution service
install    : |
    %make_install install-bin install-docs install-icons install-bootstrap install-desktop

    # Integrate with LSI+Snap.
    mv $installdir/usr/bin/steam $installdir/usr/lib/steam/.
    install -D -d -m 00755 $installdir/meta/gui/
    mv $installdir/usr/share/applications/*.desktop $installdir/meta/gui/.
    rmdir $installdir/usr/share/applications
