name       : lsb-release
version    : 1.4
release    : 20
source     :
    - https://netix.dl.sourceforge.net/project/lsb/lsb_release/1.4/lsb-release-1.4.tar.gz : 99321288f8d62e7a1d485b7c6bdccf06766fb8ca603c6195806e4457fdf17172
license    : GPL-2.0
summary    : LSB status script
# We're not actually LSB compliant.
component  : system.utils
description: |
    The lsb_release script gives information about the Linux Standards Base (LSB) status of the distribution.
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-support-for-SNAP-root-to-find-lsb-release-file.patch
build      : |
    %make
install    : |
    install -D -m 00755 lsb_release $installdir/bin/lsb_release
    install -D -m 00644 $pkgfiles/lsb-release $installdir/etc/lsb-release
